version: '3.9'

services:
  postgres:
    image: postgres:14.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=users
